# Generated by Django 2.1.3 on 2018-11-14 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('taggers', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='taggers', to=settings.AUTH_USER_MODEL)),
                ('tagging_session_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trajectory',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('geojson', djongo.models.fields.DictField()),
                ('total_points', models.IntegerField()),
                ('average_sampling', models.FloatField()),
                ('total_distance_traveled', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TrajectoryFeature',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('values', djongo.models.fields.ListField()),
                ('std', models.FloatField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('mean', models.FloatField()),
                ('median', models.FloatField()),
                ('percentile_10', models.FloatField()),
                ('percentile_25', models.FloatField()),
                ('percentile_50', models.FloatField()),
                ('percentile_75', models.FloatField()),
                ('percentile_90', models.FloatField()),
                ('trajectory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Trajectory')),
            ],
        ),
        migrations.AddField(
            model_name='database',
            name='trajectories',
            field=djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.DO_NOTHING, to='Management.Trajectory'),
        ),
    ]
