# Generated by Django 2.1.3 on 2018-11-14 16:11

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POI_ROI',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('geojson', djongo.models.fields.DictField()),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('POI', 'POI'), ('ROI', 'ROI')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='database',
            name='trajectories',
        ),
        migrations.AddField(
            model_name='trajectory',
            name='db',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Management.Database'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poi_roi',
            name='db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Database'),
        ),
    ]
