# Generated by Django 2.1.3 on 2018-11-19 14:43

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_auto_20181114_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='labels',
            field=djongo.models.fields.ListField(default=None),
            preserve_default=False,
        ),
    ]
