# Generated by Django 2.1.5 on 2019-01-10 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrajectorySegmentation',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('segmentation', djongo.models.fields.ListField()),
                ('trajectory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Management.Trajectory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
